#!/bin/sh

mkdir -p www/bio

lowdown -s -D html-skiphtml -D html-head-ids -D smarty ./src/index.md > ./www/index.html

cd ./src/bio || exit 1
for file in *.md
do
	lowdown -s -D html-skiphtml -D html-head-ids -D smarty "${file}" > "../../www/bio/${file%\.md}.html"
done

cd ../../ || exit 1

cp -R -f src/img www/ 
cp -R -f src/css www/

