#+begin_intro
* Brendon O'Laney
** Resume
#+end_intro

*** Technologies

-----

**** Day-to-day comfort

- Ruby
- Python
- C#
- Javascript / jQuery
- Typescript
- HTML5 / CSS3
- Angular 1
- AJAX
- AWS
- PostgreSQL
- MySQL
- Ruby on Rails
- Performance profiling (Rubyprof, flamegraph etc.)
- Django
- ASP.NET Core / Dotnet Core
- Linux / BSD / Bash
- Version Control (GIT / SVN)
- Foundation
- Responsive Layout and Design
- Agile Methodology
- Test Driven Development
- Cross-Browser Compatibility
- Mobile First Thinking

**** Experience with

- Golang
- C
- Node.js
- Grunt
- Backbone.js
- D3

*** Work Experience

-----

**** Software Developer

***** [[https://www.clio.com/][Clio]], Burnaby, BC, January 2019 - Present

My first months at Clio were primarily spent analyzing and optimizing the
performance of the Ruby on Rails application. My work pays close attention to
caching values, and optimizing database queries. I have also had the
opportunity to do a significant refactor on a microservice written in Golang.

Since then I have had the opportunity to build a brand new feature, the
[[Firm Dashboard][./fd.html]]

-----

**** Software Developer

***** [[https://www.socialnature.com/][SocialNature]], Vancouver, BC, April 2017 - October 2018

I Worked initially to bring new features to the web site such as the Store
Locator feature, and quickly moved into more mission critical tasks. My
greatest achievement was the Automation Engine which enabled the company to be
much more responsive to customer demand. We used a variant of the Agile
methodology that focused on one week sprints, with a strong commitment to
delivering promised units of work. The tech stack was C#, Dotnet Core, ASP.NET
Core, EntityFramework, PostgreSQL, Angular, jQuery, Foundation, Git, and AWS.

-----

**** Software Developer

***** Coho Data, Vancouver, BC, August 2016 - March 2017

My responsibilities included developing API endpoints, and front end for the web
GUI for the Coho Data storage appliance. The tech stack was Flask, jQuery,
Handlebars, and Backbone.js. We also began work on a ground-up
re-implementation of the UI featuring an API defined in Swagger (still on top
of Flask), and a brand new front end in React.

-----

**** Web Developer

***** [[https://www.fortinet.com/][Fortinet]] [3], Burnaby, BC, August 2012 - August 2016

At Fortinet I developed the Web interface for the FortiAuthenticator security
appliance. The stack was primarily Python/Django, PostgreSQL, and jQuery.
However, I found it at times necessary to modify, or write operating system
level libraries in C in order to add new features.

-----

*** Education

**** Bachelor of Computing Science

Simon Fraser University, Burnaby, BC, September 2009 - August 2012

